# Generated by Django 5.1 on 2024-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie_data",
            name="typ",
            field=models.CharField(default="action", max_length=200),
        ),
    ]
