# Generated by Django 5.1 on 2024-09-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_data_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie_data",
            name="img",
            field=models.ImageField(
                default="Images/None/Noimg.jpg", upload_to="Images/"
            ),
        ),
    ]
